### ISSUE TITLE
I just cant get it to work with pipes/belts

### ISSUE THREAD

**Issue by Hexagon37** [Epp-s-Satisfactory-Mods/AutoLink#11]
Before i say anything i want to ask how you built the tileable blueprint?

Im trying a similar thing and no matter how i try and build it my conveyors will connect but not my pipes, or my pipes will connect but not my conveyors, etc etc. im sure im doing something wrong. but i cant figure out why it wont work

**Comment by Hexagon37** [comment]
in fact i cant get it to work with pipes at all

**Comment by Epp-code** [comment]
Hey there, to build the blueprint in the sample video, I built two coal generators side-by-side and wired up the splitters and the pipes/junctions in the blueprint designer. Then I deconstructed the first coal generator (and incoming belt/pipe) and the first splitter and pipe junction. Then I saved the blueprint. By first building them manually and connecting them to actual objects, I can make sure everything is the correct length.

Be sure you're building on foundations, too. They snap buildings exactly like the blueprint designer so there's no guesswork about getting things exactly close enough. From experimenting, that's pretty close to impossible u less you're building on foundations.

If that doesn't solve your problem, be sure to let me know what version of the mod you're using.

**Comment by Hexagon37** [comment]
Hello, thanks for the response! 

That’s what I’ve been doing, and then I tried rebuilding the pipes (as placing a junction over an already built pipe makes it longer than just building normally) and that didn’t help either. 

The weird thing was when I tried with coal generators the pipes worked but not the conveyors, and when I went back to trying it with refineries the conveyors would work but not the pipes

and yes I’m using foundations! I tried to mimick everything in the demo video as best as possible 

the version of the mod should be the most recent, as I just downloaded it today from the satisfactory mod manager app

**Comment by Epp-code** [comment]
Hmm, this is the first time I've had a report like this and I can't think of a reason the mod would be inconsistent (unless maybe you had really weird/tight turns in your pipes, but even those I think I've resolved). Try simpler scenarios (like two short pipe or belt blueprints built against each other) to see if those work. If they both DO work, then there's probably something wrong with your blueprints that I can't determine from the description. If you can upload screenshots or videos, I might be able to tell from those.

Also, I did release a new version about 24 hours ago but that was just a rebuild without any code changes, so it shouldn't have affected functionality. You can try downgrading to the previous version to check if that behaves differently (I can't myself as I'm away from my computer for a couple weeks).

**Comment by Hexagon37** [comment]
For sure, using a blueprint of just pipe+junction and then conveyor belts worked fine!
But when i went back to my refinery blueprint it wouldnt work at all. 

Heres an image of the blueprint im trying to use.
![20241221113008_1](https://github.com/user-attachments/assets/f3569d19-2a75-4857-80a2-ef099bf04fc8)

Also i can confirm going back a mod version did not resolve the issue

**Comment by Epp-code** [comment]
Ok, thanks for confirming with simple tests and for testing with the previous version of the mod. Good to know I didn't somehow break something new with the new upload.

At this point, I can think of only a couple possibilities:

1) The blueprint looks aligned but somehow isn't. Can you build a few on some foundations and either post screenshots or a video of the construction process?

2) There is something about the specific type of pipe or belt that doesn't work. This would be a big surprise but can you tell me exactly which models you're building with?. And can you try with the simplest Mark 1 belts/pipes and see what that does? If it works, upgrade those in the blueprint and try again.

**Comment by Hexagon37** [comment]
For sure!

Here is the response for #1, ill try #2 later!

https://www.dropbox.com/scl/fi/11x6futbbrnhx2ljst8r9/Satisfactory-2024-12-21-12-25-23.mp4?rlkey=ktrqxub69bzbrjg9g5ebf4q4r&st=bti3iah8&dl=0

**Comment by Epp-code** [comment]
Thanks for the video! It does look like it should be working. If you disassemble and rebuild one of the buildings in that video with a working pipe, does it automatically hook back up to the pipe?

Can you also show me a case where the pipe works and the conveyor doesn't?

Sorry to be doing all this remote debugging... would be a lot easier if I could experiment myself.

It's possible that CSS changed something in recent patches that broke the mod and you're the first to report it.

**Comment by Hexagon37** [comment]
For sure!

Yes, if i delete a refinery and then place it back the refinery collects both water and the conveyor input.

I actually cant get that to happen at all so that might have been an error on my end. the case where the conveyor doesnt work seems to be user error as it happens when the secondary conveyor clips into the splitter, which im assuming it needs to connect perfectly (meaning the conveyor has to be rebuilt to the splitter in the blueprint to shorten it)

all good, hopefully im able to help!

Im not able to get the pipes to work at all, conveyors work fine when i get the length right. trying the same fix with the pipes doesnt return anything different

Using MK.1 Pipes made no difference either, both arent working for me

**Comment by Epp-code** [comment]
So I finally got back to my computer and just tested against the current Satisfactory build and AutoLink is still working fine for me - both pipes and belts link up when I build my blueprints.  To be extra sure, I freshly installed the latest version of the mod with the mod manager and tried remaking the sample video blueprint from scratch (but with the fluid fullness indicators you used in your video) and it still worked.

Even though I didn't see anything wrong from the video you posted, I can't eliminate the possibility that something wrong with the blueprint - if you want to share your blueprint file with me, I can try using it from my end.

Other than that, I'm wondering if something is wrong the mod install (have you tried reinstalling it?) or you have a conflicting mod installed.  If you have any other mods installed, try uninstalling all of them and seeing if AutoLink works by itself with nothing else. (And if that does happen to fix it, please let me know which other mods you had installed that broke AutoLink)

**Comment by Hexagon37** [comment]
Interesting!

I tried reinstalling the mod as well as running it by itself without any other mods active and im still unable to get it to work. 

I tried the blueprint again where i rebuilt everything so it lines up better, then another blueprint where i just placed the splitters/junctions over the pipes (resulting in everything overlapping, and thus not working)

Ill send the blueprints in a moment

Test 1 = place conveyors/pipes in a long line, then splitters/junctions over top, connect everything, then rebuild the connecting pipes and conveyors so that rather than overlapping they line up seamlessly, delete extra lines/junctions to create tileable blueprint

Test 2 = place everything the same, but leave everything overlapping (when you place conveyors/junctions over existing lines they overlap much more than if you place separately, figured that may be an issue) and that causes conveyors not to work either, likely as they overlap, then delete extra lines/junctions to create tileable blueprint as before

**Comment by Epp-code** [comment]
Well, that last edit showed me what's going on - apparently the mod isn't autolinking pipe junctions when you build them; I just reproduced that.  It definitely should so I'll investigate further.  Thanks for the report!

**Comment by Epp-code** [comment]
Pipe junctions should be fixed in 0.5.7.  Please let me know if you hit any other issues.
